/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/common/AppHeader.vue')['default']
    AppSidebar: typeof import('./../components/common/AppSidebar.vue')['default']
    ChapterTree: typeof import('./../components/knowledge/ChapterTree.vue')['default']
    ChatPanel: typeof import('./../components/ai/ChatPanel.vue')['default']
    CommonMistakesPanel: typeof import('./../components/learn/CommonMistakesPanel.vue')['default']
    ConcavityVisualization: typeof import('./../components/visualization/ConcavityVisualization.vue')['default']
    ConceptComparison: typeof import('./../components/deep-understanding/ConceptComparison.vue')['default']
    CounterexampleCard: typeof import('./../components/deep-understanding/CounterexampleCard.vue')['default']
    DerivativeAnimation: typeof import('./../components/visualization/DerivativeAnimation.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExampleDisplay: typeof import('./../components/knowledge/ExampleDisplay.vue')['default']
    FormulaCardDeck: typeof import('./../components/memory/FormulaCardDeck.vue')['default']
    FormulaFlashCard: typeof import('./../components/memory/FormulaFlashCard.vue')['default']
    GlobalSearch: typeof import('./../components/common/GlobalSearch.vue')['default']
    IntegralAnimation: typeof import('./../components/visualization/IntegralAnimation.vue')['default']
    InteractiveFunctionPlot: typeof import('./../components/visualization/InteractiveFunctionPlot.vue')['default']
    KnowledgeGraph: typeof import('./../components/knowledge/KnowledgeGraph.vue')['default']
    LearningPathPanel: typeof import('./../components/learn/LearningPathPanel.vue')['default']
    LimitAnimation: typeof import('./../components/visualization/LimitAnimation.vue')['default']
    MathKeyboard: typeof import('./../components/graph/MathKeyboard.vue')['default']
    MeanValueAnimation: typeof import('./../components/visualization/MeanValueAnimation.vue')['default']
    MonotonicityVisualization: typeof import('./../components/visualization/MonotonicityVisualization.vue')['default']
    NotesSection: typeof import('./../components/knowledge/NotesSection.vue')['default']
    PracticeHintSystem: typeof import('./../components/practice/PracticeHintSystem.vue')['default']
    PracticeStats: typeof import('./../components/practice/PracticeStats.vue')['default']
    ProofAnimator: typeof import('./../components/deep-understanding/ProofAnimator.vue')['default']
    ReviewReminder: typeof import('./../components/memory/ReviewReminder.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutsHelp: typeof import('./../components/common/ShortcutsHelp.vue')['default']
    StepByStepGuide: typeof import('./../components/practice/StepByStepGuide.vue')['default']
    Surface3D: typeof import('./../components/visualization/Surface3D.vue')['default']
    TaylorAnimation: typeof import('./../components/visualization/TaylorAnimation.vue')['default']
  }
}
